# .github/workflows/build.yml
name: Node Build.

on: [push]

#on:
#    schedule:
#        - cron: '0 8-17 * * 1-5'

# on: [pull_request]

# on: [push, pull_request]

#on:
#    pull_request:
#        branches:
#            - develop

jobs:
    mainbuild:
 
        runs-on: ${{ matrix.os }}
     
    strategy:
        matrix:
            node-version: [12.x]
            os: [windows-latest]
         
    steps:
    - uses: actions/checkout@v1
    - name: Run node.js on latest Windows.
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install NPM and build.
      run: |
        npm ci
        npm run build